# Generated by Django 4.2.3 on 2023-07-19 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mgroup',
            options={'verbose_name': 'main group', 'verbose_name_plural': 'main groups'},
        ),
    ]
