# Generated by Django 4.2.3 on 2023-07-19 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_mgroup_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgroup_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mgroup')),
            ],
            options={
                'verbose_name': 'sub group',
                'verbose_name_plural': 'sub groups',
            },
        ),
    ]
